'use strict';
const root='/neditport2065/api';let csrf='',content,revision,tab='products',lang='en',dirty=false;
const $=id=>document.getElementById(id);
function notice(text,error=false){$('notice').textContent=text;$('notice').classList.toggle('error',error)}
async function api(path,method='GET',body){const response=await fetch(root+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body),credentials:'same-origin'});const result=await response.json();if(!response.ok){if(response.status===401){$('workspace').hidden=true;$('login-panel').hidden=false}throw Error(result.error||'Request failed')}return result}
function node(tag,text,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n}
function field(parent,label,value,onchange,options={}){const wrap=node('label',label,options.wide?'wide':'');const input=node(options.rows?'textarea':options.choices?'select':'input');if(options.choices)for(const [v,t]of options.choices){const o=node('option',t);o.value=v;input.append(o)}if(options.type)input.type=options.type;input.value=value||'';input.maxLength=options.max||20000;if(options.placeholder)input.placeholder=options.placeholder;input.addEventListener('input',()=>{onchange(input.value);dirty=true;notice('Unsaved changes')});wrap.append(input);parent.append(wrap);return input}
function textField(parent,label,obj,key,rows=false){obj[key]??={};field(parent,label,obj[key][lang],value=>{obj[key][lang]=value},{rows,wide:rows,max:rows?20000:200,placeholder:lang==='en'?'':obj[key].en||''})}
async function render(){const container=$('editor');container.replaceChildren();$('section-title').textContent={products:'Products',news:'News',about:'About',partners:'Our Partners',settings:'Contact settings',messages:'Contact inbox'}[tab];document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.tab===tab)));const list=['products','news','partners'].includes(tab);$('add').hidden=!list;$('language-label').hidden=['settings','messages'].includes(tab);$('language-note').hidden=$('language-label').hidden;
 if(list){content[tab].forEach((item,index)=>{const card=node('section',null,'item');const top=node('div',null,'item-header');top.append(node('h3',item.name[lang]||item.name.en||'New item'));const actions=node('div',null,'actions');for(const [label,offset]of [['↑',-1],['↓',1]]){const b=node('button',label,'secondary');b.setAttribute('aria-label',offset<0?'Move up':'Move down');b.disabled=index+offset<0||index+offset>=content[tab].length;b.onclick=()=>{[content[tab][index],content[tab][index+offset]]=[content[tab][index+offset],content[tab][index]];dirty=true;render();notice('Unsaved changes')};actions.append(b)}const del=node('button','Remove','danger');del.onclick=()=>{if(confirm('Remove this item? It will be removed from the site when you save.')){content[tab].splice(index,1);dirty=true;render();notice('Unsaved changes')}};actions.append(del);top.append(actions);card.append(top);const grid=node('div',null,'grid');textField(grid,tab==='news'?'Title':'Name',item,'name');field(grid,'Status',item.status,v=>item.status=v,{choices:tab==='products'?[['draft','Hidden'],['coming-soon','Coming soon'],['published','Published']]:[['draft','Draft / hidden'],['published','Published']]});textField(grid,tab==='news'?'Article text':'Description',item,'description',true);field(grid,'Image URL (HTTPS or /static/img/ path)',item.image,v=>item.image=v,{max:2000});if(tab!=='news')field(grid,'Website URL (HTTPS)',item.url,v=>item.url=v,{max:2000});else field(grid,'Publication date',item.date,v=>item.date=v,{type:'date'});card.append(grid);container.append(card)});if(!content[tab].length)container.append(node('p','No items yet. Add one to get started.'))}
 if(tab==='about'){const card=node('section',null,'item');for(const [key,label]of [['lead','Introduction'],['ownership','Brand ownership'],['mission','Our mission'],['approach','Our approach']])textField(card,label,content.about,key,true);container.append(card)}
 if(tab==='settings'){const card=node('section',null,'item');card.append(node('p','Route each contact topic to its own mailbox. Messages are also kept in the inbox.'));for(const key of ['sales','support','info'])field(card,key[0].toUpperCase()+key.slice(1)+' recipient',content.recipients[key],v=>content.recipients[key]=v,{type:'email',max:254});container.append(card);try{const s=await api('/session');card.append(node('p',s.emailConfigured?'Email delivery is configured. Check the inbox for delivery status.':'Email delivery is not configured yet. Messages are received in the inbox.'))}catch(e){notice(e.message,true)}}
 if(tab==='messages'){container.append(node('p','Loading messages…'));try{const messages=await api('/messages');if(tab!=='messages')return;container.replaceChildren();container.append(node('p','Latest 100 messages. “Received” means saved here; “emailed” confirms SMTP accepted the email.'));for(const m of messages){const card=node('article',null,'item');card.append(node('h3',m.name+' · '+m.topic),node('p',m.email+' · '+m.company+' · '+new Date(m.created).toLocaleString(),'message-meta'),node('p',m.message,'message-body'),node('p','Delivery: '+m.status+' · Recipient: '+m.recipient,'message-meta'));container.append(card)}if(!messages.length)container.append(node('p','No messages yet.'))}catch(e){notice(e.message,true)}}
}
async function load(){const result=await api('/content');content=result.content;revision=result.revision;dirty=false;await render()}
async function enter(){const session=await api('/session');csrf=session.csrf;await load();$('login-panel').hidden=true;$('workspace').hidden=false;notice('')}
$('login-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const f=new FormData(e.target);const result=await api('/login','POST',{username:f.get('username'),password:f.get('password')});csrf=result.csrf;e.target.elements.password.value='';await enter()}catch(err){notice(err.message,true)}finally{button.disabled=false}};
$('save').onclick=async()=>{if(!dirty){notice('No changes to save');return}const snapshot=JSON.stringify(content);$('save').disabled=true;try{const result=await api('/content','PUT',{content:JSON.parse(snapshot),revision});revision=result.revision;dirty=JSON.stringify(content)!==snapshot;notice(dirty?'Saved. You have additional unsaved changes.':'Saved. Published content is now live.')}catch(e){notice(e.message,true)}finally{$('save').disabled=false}};
$('reload').onclick=async()=>{if(dirty&&!confirm('Discard unsaved changes and reload?'))return;try{await load();notice('Content reloaded')}catch(e){notice(e.message,true)}};
$('logout').onclick=async()=>{if(dirty&&!confirm('Discard unsaved changes and sign out?'))return;try{await api('/logout','POST',{});dirty=false;content=null;csrf='';$('workspace').hidden=true;$('login-panel').hidden=false;notice('Signed out')}catch(e){notice(e.message,true)}};
$('tabs').onclick=e=>{if(e.target.dataset.tab){tab=e.target.dataset.tab;render()}};$('language').onchange=e=>{lang=e.target.value;render()};$('add').onclick=()=>{content[tab].push({id:crypto.randomUUID(),name:{en:''},description:{en:''},image:'',url:'',status:'draft',date:new Date().toISOString().slice(0,10)});dirty=true;render();notice('New draft added. Fill in the fields and save.');$('editor').lastElementChild.scrollIntoView({behavior:'smooth',block:'center'})};window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});enter().catch(e=>{if(e.message!=='Please sign in')notice(e.message,true)});
